//-----------------------------------------------------------------------------
// main_zc702.v
// Top-level for ztachip on Xilinx Zynq ZC702 (XC7Z020CLG484-1)
//
// Architecture:
//
//   [Zynq PS7]
//     FCLK_CLK0 (100 MHz) ──────────────────────────────┐  (was 125, lowered for timing)
//     FCLK_CLK1 (200 MHz) ──────────────────────────────┤  (MUST be exactly 2x FCLK0)
//     FCLK_CLK2 ( 24 MHz) ──────────────────────────────┤  [soc_base (VHDL)]
//     FCLK_CLK3 ( 25 MHz) ──────────────────────────────┤    VexRiscv (RISC-V)
//     FCLK_RESET0_N ────────────────────────────────────┤    ztachip accelerator
//     S_AXI_HP0 (64-bit AXI3 slave) ←── SDRAM AXI ─────┘    TCM (BRAM)
//     DDR3 (1 GB, connected to PS) ───── via HP0
//
// Key differences from Arty A7-100T design:
//   1. No external DDR3 pins (PS manages DDR3 directly)
//   2. No sys_clock external oscillator (PS FCLK drives PL)
//   3. No Xilinx MIG DDR controller (PS HP0 replaces it)
//   4. No clk_wiz (PS FCLK synthesizes all needed clocks)
//   5. exmem_data_width_c = 64 (HP0 is 64-bit wide)
//
// Peripheral status for minimal port:
//   UART  : Internal only. Add XDC pin + external USB-UART on FMC for console.
//   LED   : Internal only. Use Vivado ILA or add FMC pin mapping.
//   VGA   : Stubbed (no VGA Pmod on ZC702). Add FMC daughter card later.
//   Camera: Stubbed (no OV7670 on ZC702). Add FMC daughter card later.
//   ETH   : Stubbed (use PS GEM via ARM if needed later).
//
// Dependencies (generated by Vivado from zynq_ps_bd.tcl):
//   zynq_system_wrapper.v  -- auto-generated BD wrapper
//
// ARLEN note:
//   soc_base SDRAM_arlen is 8-bit (AXI4 field). ztachip max burst = 9.
//   HP0 expects 4-bit AXI3 ARLEN. Safe to connect [3:0] only since
//   ztachip values never exceed 9 (i.e., upper 4 bits are always 0).
//-----------------------------------------------------------------------------

module main_zc702 (
    //--------------------------------------------------------------------------
    // Zynq PS DDR3 interface - REQUIRED by PS7, auto-constrained by BD.
    // DO NOT add these to main_zc702.xdc - the block design handles them.
    //--------------------------------------------------------------------------
    inout [14:0]  DDR_addr,
    inout [2:0]   DDR_ba,
    inout         DDR_cas_n,
    inout         DDR_ck_n,
    inout         DDR_ck_p,
    inout         DDR_cke,
    inout         DDR_cs_n,
    inout [3:0]   DDR_dm,
    inout [31:0]  DDR_dq,
    inout [3:0]   DDR_dqs_n,
    inout [3:0]   DDR_dqs_p,
    inout         DDR_odt,
    inout         DDR_ras_n,
    inout         DDR_reset_n,
    inout         DDR_we_n,

    //--------------------------------------------------------------------------
    // Zynq PS FIXED_IO (MIO bank, JTAG, power) - REQUIRED by PS7.
    // DO NOT add to main_zc702.xdc - the block design handles them.
    //--------------------------------------------------------------------------
    inout         FIXED_IO_ddr_vrn,
    inout         FIXED_IO_ddr_vrp,
    inout [53:0]  FIXED_IO_mio,
    inout         FIXED_IO_ps_clk,
    inout         FIXED_IO_ps_porb,
    inout         FIXED_IO_ps_srstb,

    //--------------------------------------------------------------------------
    // UART — FMC LPC J61 connector (LA02_P=TX, LA02_N=RX, 1.8V LVCMOS)
    // Connect a USB-UART adapter here to see chatbot output at 115200 baud.
    //--------------------------------------------------------------------------
    output        UART_TXD,
    input         UART_RXD
);

    //--------------------------------------------------------------------------
    // Internal clocks and reset from PS FCLK outputs
    //--------------------------------------------------------------------------
    wire clk_ref;       // 93.75 MHz reference from PS FCLK0 -> feeds PL MMCM
    wire clk_main;      // 93.75 MHz - main PL clock (from MMCM clk_out1)
    wire clk_x2_main;   // 187.5 MHz - double-speed clock (MMCM clk_out2, exactly 2x)
    wire clk_camera;    //  24 MHz - OV7670 master clock (PS FCLK2)
    wire clk_vga;       //  25 MHz - VGA pixel clock (PS FCLK3)
    wire fclk1_unused;  // PS FCLK1 no longer used (clk_x2 now comes from the MMCM)
    wire reset_n;       // Active-low reset from PS (FCLK_RESET0_N)
    wire mmcm_locked;   // MMCM locked indicator
    wire soc_reset_n;   // reset_n gated by mmcm_locked -> soc_base reset

    // Hold soc_base in reset until BOTH the PS releases reset AND the MMCM locks.
    // clk_main / clk_x2_main come from the SAME MMCM -> phase-aligned exact 2x,
    // giving Vivado a common clock root so the cross-clock HOLD paths close.
    assign soc_reset_n = reset_n & mmcm_locked;

    //--------------------------------------------------------------------------
    // AXI3 HP0 signals (64-bit) - ztachip DMA to Zynq PS DDR3
    // Signal naming convention: hp0_* mirrors soc_base SDRAM_* port names.
    //
    // NOTE on ARLEN/AWLEN width:
    //   soc_base exposes 8-bit SDRAM_arlen (AXI4 field).
    //   HP0 port is AXI3 with 4-bit ARLEN. Since ztachip max burst = 9,
    //   we connect only [3:0] - the upper 4 bits are always 0.
    //--------------------------------------------------------------------------

    // Read address channel
    wire [31:0]  hp0_araddr;
    wire [1:0]   hp0_arburst;
    wire [7:0]   hp0_arlen;    // Full 8-bit from soc_base; [3:0] goes to HP0
    wire         hp0_arready;
    wire [2:0]   hp0_arsize;
    wire         hp0_arvalid;

    // Write address channel
    wire [31:0]  hp0_awaddr;
    wire [1:0]   hp0_awburst;
    wire [7:0]   hp0_awlen;    // Full 8-bit from soc_base; [3:0] goes to HP0
    wire         hp0_awready;
    wire [2:0]   hp0_awsize;
    wire         hp0_awvalid;

    // Write response channel
    wire         hp0_bready;
    wire [1:0]   hp0_bresp;
    wire         hp0_bvalid;

    // Read data channel
    wire [63:0]  hp0_rdata;
    wire         hp0_rlast;
    wire         hp0_rready;
    wire [1:0]   hp0_rresp;
    wire         hp0_rvalid;

    // Write data channel
    wire [63:0]  hp0_wdata;
    wire         hp0_wlast;
    wire         hp0_wready;
    wire [7:0]   hp0_wstrb;
    wire         hp0_wvalid;

    //--------------------------------------------------------------------------
    // Unused peripheral outputs from soc_base (stubbed for minimal port)
    //--------------------------------------------------------------------------
    wire [3:0]  led_nc;
    // uart_txd_nc removed — UART now routed to FMC J61 LA02_P/N pins
    wire        vga_hs_nc, vga_vs_nc;
    wire [3:0]  vga_r_nc, vga_b_nc, vga_g_nc;
    wire        cam_scl_nc, cam_rst_nc, cam_sdr_nc, cam_mclk_nc, cam_pwdn_nc;
    wire [19:0] apb_paddr_nc;
    wire [15:0] apb_penable_nc;
    wire        apb_pwrite_nc;
    wire [31:0] apb_pwdata_nc;

    //==========================================================================
    // Zynq PS Block Design Wrapper
    // Generated by Vivado from zynq_ps_bd.tcl as zynq_system_wrapper.v
    //==========================================================================
    zynq_system_wrapper ps_inst (
        // PS DDR3 (pass-through to package pins)
        .DDR_addr       (DDR_addr),
        .DDR_ba         (DDR_ba),
        .DDR_cas_n      (DDR_cas_n),
        .DDR_ck_n       (DDR_ck_n),
        .DDR_ck_p       (DDR_ck_p),
        .DDR_cke        (DDR_cke),
        .DDR_cs_n       (DDR_cs_n),
        .DDR_dm         (DDR_dm),
        .DDR_dq         (DDR_dq),
        .DDR_dqs_n      (DDR_dqs_n),
        .DDR_dqs_p      (DDR_dqs_p),
        .DDR_odt        (DDR_odt),
        .DDR_ras_n      (DDR_ras_n),
        .DDR_reset_n    (DDR_reset_n),
        .DDR_we_n       (DDR_we_n),

        // PS MIO/JTAG (pass-through to package pins)
        .FIXED_IO_ddr_vrn (FIXED_IO_ddr_vrn),
        .FIXED_IO_ddr_vrp (FIXED_IO_ddr_vrp),
        .FIXED_IO_mio     (FIXED_IO_mio),
        .FIXED_IO_ps_clk  (FIXED_IO_ps_clk),
        .FIXED_IO_ps_porb (FIXED_IO_ps_porb),
        .FIXED_IO_ps_srstb(FIXED_IO_ps_srstb),

        // PL Fabric clocks (outputs from PS)
        .FCLK_CLK0     (clk_ref),       // 93.75 MHz reference -> PL MMCM input
        .FCLK_CLK1     (fclk1_unused),  // unused (clk_x2_main now from MMCM)
        .FCLK_CLK2     (clk_camera),
        .FCLK_CLK3     (clk_vga),
        .FCLK_RESET0_N (reset_n),

        // HP0 AXI3 slave - read address channel
        .S_AXI_HP0_araddr  (hp0_araddr),
        .S_AXI_HP0_arburst (hp0_arburst),
        .S_AXI_HP0_arcache (4'b0011),       // Cacheable, non-bufferable
        .S_AXI_HP0_arid    (6'b0),           // No transaction IDs used
        .S_AXI_HP0_arlen   (hp0_arlen[3:0]), // AXI3: 4-bit. Safe: max=9<16
        .S_AXI_HP0_arlock  (2'b0),           // Normal access
        .S_AXI_HP0_arprot  (3'b0),           // Unprivileged, non-secure, data
        .S_AXI_HP0_arqos   (4'b0),
        .S_AXI_HP0_arready (hp0_arready),
        .S_AXI_HP0_arsize  (hp0_arsize),
        .S_AXI_HP0_arvalid (hp0_arvalid),

        // HP0 AXI3 slave - write address channel
        .S_AXI_HP0_awaddr  (hp0_awaddr),
        .S_AXI_HP0_awburst (hp0_awburst),
        .S_AXI_HP0_awcache (4'b0011),
        .S_AXI_HP0_awid    (6'b0),
        .S_AXI_HP0_awlen   (hp0_awlen[3:0]),
        .S_AXI_HP0_awlock  (2'b0),
        .S_AXI_HP0_awprot  (3'b0),
        .S_AXI_HP0_awqos   (4'b0),
        .S_AXI_HP0_awready (hp0_awready),
        .S_AXI_HP0_awsize  (hp0_awsize),
        .S_AXI_HP0_awvalid (hp0_awvalid),

        // HP0 AXI3 slave - write response channel
        .S_AXI_HP0_bid     (),               // Ignore returned IDs
        .S_AXI_HP0_bready  (hp0_bready),
        .S_AXI_HP0_bresp   (hp0_bresp),
        .S_AXI_HP0_bvalid  (hp0_bvalid),

        // HP0 AXI3 slave - read data channel
        .S_AXI_HP0_rdata   (hp0_rdata),
        .S_AXI_HP0_rid     (),
        .S_AXI_HP0_rlast   (hp0_rlast),
        .S_AXI_HP0_rready  (hp0_rready),
        .S_AXI_HP0_rresp   (hp0_rresp),
        .S_AXI_HP0_rvalid  (hp0_rvalid),

        // HP0 AXI3 slave - write data channel
        .S_AXI_HP0_wdata   (hp0_wdata),
        .S_AXI_HP0_wid     (6'b0),          // AXI3 requires WID (tied to 0)
        .S_AXI_HP0_wlast   (hp0_wlast),
        .S_AXI_HP0_wready  (hp0_wready),
        .S_AXI_HP0_wstrb   (hp0_wstrb),
        .S_AXI_HP0_wvalid  (hp0_wvalid),

        // HP0 clock (PL side must be driven from PL)
        .S_AXI_HP0_ACLK    (clk_main)
    );

    //==========================================================================
    // PL Clock generator (MMCM) — generates clk_main (93.75) and clk_x2_main
    // (187.5) from a SINGLE source so the two clocks share a common root.
    //
    // WHY: ztachip's dual-pumped memories require clk_x2_main to be an exactly-
    // 2x, phase-aligned copy of clk_main. Driving them from two separate PS
    // FCLK buffers left them with NO common node, so Vivado applied full clock
    // pessimism on the cross-clock paths and HOLD timing failed (-43 ps).
    // One MMCM -> shared root -> clock pessimism removal -> hold closes.
    // This mirrors the original ztachip (Arty) clk_wiz approach.
    //==========================================================================
    clk_mmcm clk_mmcm_inst (
        .clk_in1  (clk_ref),       // 93.75 MHz from PS FCLK0
        .resetn   (reset_n),       // active-low reset from PS
        .clk_out1 (clk_main),      //  93.75 MHz
        .clk_out2 (clk_x2_main),   // 187.5 MHz (exactly 2x, phase aligned)
        .locked   (mmcm_locked)
    );

    //==========================================================================
    // soc_base: VexRiscv (RISC-V) + ztachip accelerator + TCM
    //
    // SDRAM_clk = clk_main: both ztachip DMA and HP0 are in the same 100 MHz
    // clock domain, eliminating any clock-domain-crossing complexity.
    //==========================================================================
    soc_base soc_base_inst (
        //----------------------------------------------------------------------
        // Clocks and reset
        //----------------------------------------------------------------------
        .clk_main       (clk_main),
        .clk_x2_main    (clk_x2_main),
        .clk_camera     (clk_camera),
        .clk_vga        (clk_vga),
        .clk_reset      (soc_reset_n),

        //----------------------------------------------------------------------
        // SDRAM AXI master -> Zynq PS HP0
        // SDRAM_clk = clk_main 100 MHz (same as S_AXI_HP0_ACLK - single clock domain)
        //----------------------------------------------------------------------
        .SDRAM_clk      (clk_main),
        .SDRAM_reset    (soc_reset_n),

        .SDRAM_araddr   (hp0_araddr),
        .SDRAM_arburst  (hp0_arburst),
        .SDRAM_arlen    (hp0_arlen),
        .SDRAM_arready  (hp0_arready),
        .SDRAM_arsize   (hp0_arsize),
        .SDRAM_arvalid  (hp0_arvalid),

        .SDRAM_awaddr   (hp0_awaddr),
        .SDRAM_awburst  (hp0_awburst),
        .SDRAM_awlen    (hp0_awlen),
        .SDRAM_awready  (hp0_awready),
        .SDRAM_awsize   (hp0_awsize),
        .SDRAM_awvalid  (hp0_awvalid),

        .SDRAM_bready   (hp0_bready),
        .SDRAM_bresp    (hp0_bresp),
        .SDRAM_bvalid   (hp0_bvalid),

        .SDRAM_rdata    (hp0_rdata),
        .SDRAM_rlast    (hp0_rlast),
        .SDRAM_rready   (hp0_rready),
        .SDRAM_rresp    (hp0_rresp),
        .SDRAM_rvalid   (hp0_rvalid),

        .SDRAM_wdata    (hp0_wdata),
        .SDRAM_wlast    (hp0_wlast),
        .SDRAM_wready   (hp0_wready),
        .SDRAM_wstrb    (hp0_wstrb),
        .SDRAM_wvalid   (hp0_wvalid),

        //----------------------------------------------------------------------
        // APB peripheral bus - stubbed (no external APB slaves)
        // PREADY=1 gives immediate ACK to any CPU APB access (reads return 0).
        // Note: If firmware initializes Ethernet, it will read 0 from registers
        // and may time out. Disable Ethernet init in firmware if this occurs.
        //----------------------------------------------------------------------
        .APB_PADDR_OUT    (apb_paddr_nc),
        .APB_PENABLE_OUT  (apb_penable_nc),
        .APB_PREADY_IN    (1'b1),
        .APB_PWRITE_OUT   (apb_pwrite_nc),
        .APB_PWDATA_OUT   (apb_pwdata_nc),
        .APB_PRDATA_IN    (32'h0),
        .APB_PSLVERROR_IN (1'b0),

        //----------------------------------------------------------------------
        // GPIO - stubbed (no physical LEDs/buttons connected for minimal port)
        // To add: expose led/pushbutton in port list and add XDC constraints.
        //----------------------------------------------------------------------
        .led        (led_nc),
        .pushbutton (4'b0000),

        //----------------------------------------------------------------------
        // UART - connected to FMC LPC J61 LA02_P/N (1.8V, 115200 baud)
        //----------------------------------------------------------------------
        .UART_TXD (UART_TXD),
        .UART_RXD (UART_RXD),

        //----------------------------------------------------------------------
        // VGA - stubbed (no VGA Pmod on ZC702)
        // To enable: add FMC HDMI/VGA card and update XDC + port list.
        //----------------------------------------------------------------------
        .VGA_HS_O (vga_hs_nc),
        .VGA_VS_O (vga_vs_nc),
        .VGA_R    (vga_r_nc),
        .VGA_B    (vga_b_nc),
        .VGA_G    (vga_g_nc),

        //----------------------------------------------------------------------
        // Camera (OV7670) - stubbed (no camera Pmod on ZC702)
        // CAMERA_PCLK/VS/D/RS = 0 (inactive).
        // To enable: add FMC camera card and update XDC + port list.
        //----------------------------------------------------------------------
        .CAMERA_SCL   (cam_scl_nc),
        .CAMERA_VS    (1'b0),
        .CAMERA_PCLK  (1'b0),
        .CAMERA_D     (8'h00),
        .CAMERA_RESET (cam_rst_nc),
        .CAMERA_SDR   (cam_sdr_nc),
        .CAMERA_RS    (1'b0),
        .CAMERA_MCLK  (cam_mclk_nc),
        .CAMERA_PWDN  (cam_pwdn_nc)
    );

endmodule
